model:
  name: vit
  transformer:
    embed_dim: 768
    num_encoder_layers: 12
    num_heads: 12
    dim_feedforward: 3072
    dropout: 0.1
    activation: gelu
    final_norm: True
    norm_eps: 1.0e-6
  patch_embed:
    name: vit_like
    img_size: 224
    patch_size: 16
    image_channels: 3
  pos_encoding:
    name: learnable
    dropout: Null

resume:
  imagenet: weights/deit_base_patch16_224.pth
  cifar_100: run/cifar_100/vanilla/deit_base/ckpt/best.pth
  cifar_10: run/cifar_10/vanilla/deit_base/ckpt/best.pth
  caltech_101: run/caltech_101/vanilla/deit_base/ckpt/best.pth
