dataset: config/datasets/cifar_10.yaml

discretization:
  vocabulary:
    size: 128
    dim: 768
    detach_input_seq: True
    uniform_range: [0, 1]
  encoder_layer: module.transformer.layers.9

model: config/models/deit_base_patch16_224.yaml
