dataset: config/datasets/caltech_101.yaml

discretization:
  vocabulary:
    size: 1024
    dim: 768
    detach_input_seq: True
    uniform_range: [0, 1]
  encoder_layer: module.transformer.layers.9

model: config/models/deit_base_patch16_224.yaml
